version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '17:00'
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  groups:
    chunkd:
      patterns:
        - "@chunkd/*"
    cooldown:
      default-days: 15
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 15
    ignore:
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
      - dependency-name: pkg:localrepo/localrepo/local?repository_url=target
